### ISSUE TITLE
MultiProvider 문제

### ISSUE THREAD

**Issue by kangsudal** [kangsudal/calculator_neumorphic#3]
```
======== Exception caught by widgets library =======================================================
The following assertion was thrown building ChangeNotifierProvider<Calculator>(dirty):
ChangeNotifierProvider<Calculator> used outside of MultiProvider must specify a child
'package:provider/src/inherited_provider.dart':
Failed assertion: line 158 pos 7: 'builder != null || child != null'

The relevant error-causing widget was: 
  ChangeNotifierProvider<Calculator> ChangeNotifierProvider:file:///C:/Users/kangs/AndroidStudioProjects/calculator/lib/main.dart:19:9
When the exception was thrown, this was the stack: 
#2      InheritedProvider.buildWithChild (package:provider/src/inherited_provider.dart:158:7)
#3      SingleChildStatelessElement.build (package:nested/nested.dart:277:21)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4806:15)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4787:5)
#7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4781:5)
#8      SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
...     Normal element mounting (7 frames)
#15     _NestedHookElement.mount (package:nested/nested.dart:187:11)
...     Normal element mounting (7 frames)
#22     SingleChildWidgetElementMixin.mount (package:nested/nested.dart:222:11)
#23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#24     Element.updateChild (package:flutter/src/widgets/framework.dart:3545:20)
#25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#26     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#27     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2659:19)
#28     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:891:21)
#29     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:370:5)
#30     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
#31     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083:9)
#32     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:864:7)
(elided 6 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, and dart:async-patch)
====================================================================================================
Reloaded 1 of 647 libraries in 396ms.

```

```
  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider<Calculator>(
          create: (context) => Calculator(),
          child: NeumorphicApp(
            title: 'Flutter Demo',
            themeMode: ThemeMode.light,
            theme: NeumorphicThemeData(
              baseColor: Color(0xFFF0F1F6),
              lightSource: LightSource.topLeft,
              depth: 5,
              intensity: 0.6,
            ),
            home: const MyHomePage(),
          ),
        ),
      ],
    );
  }
```

MutipleProvider에 ChangeNotifierProvider를 하나만 넣어서그런가?

**Comment by kangsudal** [comment]
```
 Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider<Calculator>(
          create: (context) => Calculator(),
        ),
      ],
      child: NeumorphicApp(
        title: 'Flutter Demo',
        themeMode: ThemeMode.light,
        theme: NeumorphicThemeData(
          baseColor: Color(0xFFF0F1F6),
          lightSource: LightSource.topLeft,
          depth: 5,
          intensity: 0.6,
        ),
        home: const MyHomePage(),
      ),
    );
  }
```

providers:[] 안에 child:까지 넣어버려서 그랬다.
밖으로 child를 빼면된다.
